version: '3.9'
services:
  tawebsite:
    container_name: tawebsite
    build: .
    ports:
      - 3000:3000
    restart: on-failure
    depends_on:
      - mysql
    env_file:
      - .env.production #important กำหนดให้ใช้ .env.production
    networks:
      - application
    volumes:
      - uploads_dir:/usr/src/app/public/uploads
  nginx:
    container_name: tawebsite_nginx
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - tawebsite
    networks:
      - application
  mysql:
    container_name: tawebsite_mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env.production
    healthcheck:
      test: ["CMD-SHELL", " netstat -an | grep -q 3306"]
      timeout: 5s
      retries: 3
    volumes:
      - "mysql_data:/var/lib/mysql"
    networks:
      - application
  phpmyadmin:
    container_name: tawebsite_phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - application
networks:
  application:
    driver: bridge
volumes:
  mysql_data:
  uploads_dir:
