version: '3.8'
services:
  tawebsite:
    container_name: tawebsite
    build: .
    ports:
      - 3000:3000
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env.production #important กำหนดให้ใช้ .env.production
    networks:
      - application
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: tawebsite
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 3
    volumes:
      - "mysql_data:/var/lib/mysql"
    networks:
      - application
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - application
networks:
  application:
    driver: bridge
volumes:
  mysql_data:
