version: '3.8'
services:
  tawebsite:
    container_name: tawebsite
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mysql
    env_file:
      - .env
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: tawebsite
    volumes:
      - "mysql_data:/var/lib/mysql"
    networks:
      - database
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - database
networks:
  database:
    driver: bridge
volumes:
  mysql_data:
