-- AlterTable
ALTER TABLE `Enroll` MODIFY `courseBenchelor` ENUM('INFORMATION_TECHNOLOGY', 'DATA_SCIENCE_AND_BUSINESS_ANALYTICS') NULL,
    MODIFY `degree` ENUM('BANCHELOR_DEGREE', 'MASTER_DEGREE') NULL,
    MODIFY `grade` ENUM('A', 'B_PLUS', 'B', 'C_PLUS', 'C', 'D_PLUS', 'D', 'F') NULL,
    MODIFY `passedInBenchelor` ENUM('INFORMATION_TECHNOLOGY', 'DATA_SCIENCE_AND_BUSINESS_ANALYTICS') NULL;
