-- AlterTable
ALTER TABLE `Enroll` ADD COLUMN `courseBenchelor` ENUM('INFORMATION_TECHNOLOGY', 'DATA_SCIENCE_AND_BUSINESS_ANALYTICS') NULL,
    ADD COLUMN `degree` ENUM('BANCHELOR_DEGREE', 'MASTER_DEGREE') NULL,
    ADD COLUMN `grade` ENUM('A', 'B_PLUS', 'B', 'C_PLUS', 'C', 'D_PLUS', 'D', 'F') NULL,
    ADD COLUMN `passedCourseId` VARCHAR(191) NULL,
    ADD COLUMN `passedCourseName` VARCHAR(191) NULL,
    ADD COLUMN `passedinBenchelor` ENUM('INFORMATION_TECHNOLOGY', 'DATA_SCIENCE_AND_BUSINESS_ANALYTICS') NULL;
